### ISSUE TITLE
0.0.2 version of this plug-in is not available on redmine2.4.1

### ISSUE THREAD

**Issue by a23764996** [twinslash/redmine_tracker_accessible#1]
0.0.2 version of this plug-in is not available on redmine2.4.1

**Comment by matheusdias** [comment]
Same thing happens in 2.5.0.stable

**Comment by serge-xxx** [comment]
guys could you please check now?

**Comment by matheusdias** [comment]
Work like a charm in Redmine 2.5.1. Thanks.
